# Generated by Django 4.2.4 on 2023-08-17 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=200)),
                ('task_description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('task_start_time', models.TimeField(default=datetime.datetime.now)),
                ('task_end_time', models.TimeField(default=datetime.datetime(2023, 8, 17, 22, 17, 58, 80748))),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
    ]
